version: '2'

services:
  frontend: 
    build: ./frontend
    working_dir: /frontend
    ports:
      - "3000:1337" 
    volumes:
      - ./frontend:/frontend
    environment:
      - REACT_APP_BACKEND_ENDPOINT=http://localhost:4000
      - PORT=1337
    depends_on:
      - backend

  backend: 
    build: ./backend
    working_dir: /backend
    ports:
      - "4000:1338" 
    links:
      - database 
    volumes:
      - ./backend:/backend
    environment:
      - DB_ADDRESS=database:27017
      - PORT=1337
      - BACKEND_PORT=1338
      - DB_NAME=gravnic-level-creator
      - LOG_LEVEL=debug
      - MORGAN_LOGGING=ON
    depends_on:
      - database

  database: 
    image: mongo 