version: '2.1'

services:
  frontend:
    build: ./frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      backend:
        condition: service_healthy
      levelsolver:
        condition: service_healthy
    environment:
      - REACT_APP_BACKEND_ENDPOINT=http://backend:4000
      - REACT_APP_LEVEL_SOLVER_ENDPOINT=http://levelsolver:5000
    env_file: ./frontend/.env
    healthcheck:
      test: "curl -f http://frontend:3000"
      interval: 10s
      timeout: 5s
      retries: 15

  backend: 
    build: ./backend
    working_dir: /backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    env_file: ./backend/.env
    environment:
      - DB_ADDRESS=database:27017
    healthcheck:
      test: "curl -f http://backend:4000/levels"
      interval: 10s
      timeout: 5s
      retries: 15

  levelsolver: 
    build: ./levelSolver
    working_dir: /levelSolver
    ports:
      - "5000:5000"
    volumes:
      - ./levelSolver:/levelSolver
    env_file: ./levelSolver/.env
    healthcheck:
      test: "curl -f http://levelsolver:5000/solveLevel/[]"
      interval: 10s
      timeout: 5s
      retries: 15
      
  e2e: 
    build: ./e2e
    working_dir: /e2e
    env_file: ./e2e/.env
    environment:
      - CI=true
      - FRONTEND_URL=frontend:3000
      - DB_ADDRESS=database:27017
      - DB_NAME=gravnic-level-creator
    depends_on:
      frontend:
        condition: service_healthy

  database: 
    image: mongo 