version: '2.1'

services:
  frontend_compile: 
    image: node:9-alpine
    working_dir: /frontend
    command: "yarn"
    volumes:
      - ./frontend:/frontend

  frontend_lint: 
    image: node:9-alpine
    working_dir: /frontend
    command: "yarn lint"
    volumes:
      - ./frontend:/frontend

  frontend_tests: 
    image: node:9-alpine
    working_dir: /frontend
    command: "yarn test"
    volumes:
      - ./frontend:/frontend
    environment:
      - CI=true

  frontend: 
    build: ./frontend
    command: "yarn start"
    working_dir: /frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_ENDPOINT=http://localhost:4000
      - PORT=3000
    healthcheck:
      test: "curl -f http://frontend:3000"
      interval: 10s
      timeout: 5s
      retries: 15

  backend_compile: 
    image: node:9-alpine
    working_dir: /backend
    command: "yarn"
    volumes:
      - ./backend:/backend

  backend_lint: 
    image: node:9-alpine
    working_dir: /frontend
    command: "yarn lint"
    volumes:
      - ./frontend:/frontend

  backend: 
    build: ./backend
    working_dir: /backend
    command: "yarn start"
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    environment:
      - DB_ADDRESS=database:27017
      - PORT=4000
      - DB_NAME=gravnic-level-creator
    healthcheck:
      test: "curl -f http://backend:4000/levels"
      interval: 10s
      timeout: 5s
      retries: 15
      
  backend_tests: 
    image: node:9-alpine
    working_dir: /backend
    command: "yarn test --forceExit"
    volumes:
      - ./backend:/backend
    environment:
      - CI=true
      - DB_NAME=gravnic-level-creator-test
      - DB_ADDRESS=database:27017
      - PORT=5001
      - LOG_LEVEL=debug
      - MORGAN_LOGGING=OFF
    depends_on:
      - database

  e2e_compile: 
    image: node:9-alpine
    working_dir: /e2e
    command: "yarn"
    volumes:
      - ./e2e:/e2e

  e2e_lint: 
    image: node:9-alpine
    working_dir: /e2e
    command: "yarn lint"
    volumes:
      - ./e2e:/e2e 

  e2e: 
    build: ./e2e
    working_dir: /e2e
    command: "yarn test"
    environment:
      - FRONTEND_URL=frontend:3000
      - CI=true
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy

  database: 
    image: mongo 