version: 2
jobs:
  build:
    machine: true
    working_directory: ~/gravnic-level-creator
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run: docker-compose run frontend_compile

      - run: docker-compose run frontend_tests

      - run: docker-compose run backend_compile

      - run: docker-compose run backend_tests

      - run: docker-compose up e2e
