version: 2

install_docker_compose: &install_docker_compose
  name: Install docker compose
  user: root
  command: |
    curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
    chmod +x ~/docker-compose
    sudo mv ~/docker-compose /usr/local/bin/docker-compose

jobs:
  build_frontend:
    machine: true
    working_directory: ~/gravnic-level-creator
    steps:
      - checkout
      - run:
          <<: *install_docker_compose
      - restore_cache:
          keys:
            - gravnic-frontend-v2-{{ checksum "frontend/yarn.lock" }}
            - gravnic-frontend-v2-
      - run: docker-compose run frontend_compile
      - save_cache:
          key: gravnic-frontend-v2-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
      - persist_to_workspace:
          root: ~/gravnic-level-creator
          paths:
            - frontend

  build_backend:
    machine: true
    working_directory: ~/gravnic-level-creator
    steps:
      - checkout
      - run:
          <<: *install_docker_compose
      - restore_cache:
          keys:
            - gravnic-backend-v2-{{ checksum "backend/yarn.lock" }}
            - gravnic-backend-v2-
      - run: docker-compose run backend_compile
      - save_cache:
          key: gravnic-backend-v2-{{ checksum "backend/yarn.lock" }}
          paths:
            - backend/node_modules
      - persist_to_workspace:
          root: ~/gravnic-level-creator
          paths:
            - backend

  frontend_tests:
    machine: true
    working_directory: ~/gravnic-level-creator
    steps:
      - checkout
      - run:
          <<: *install_docker_compose
      - attach_workspace:
          at: ~/gravnic-level-creator
      - run: docker-compose run frontend_lint
      - run: docker-compose run frontend_tests

  backend_tests:
    machine: true
    working_directory: ~/gravnic-level-creator
    steps:
      - checkout
      - run:
          <<: *install_docker_compose
      - attach_workspace:
          at: ~/gravnic-level-creator
      - run: docker-compose run backend_lint
      - run: docker-compose run backend_tests

  e2e_tests:
    machine: true
    working_directory: ~/gravnic-level-creator
    steps:
      - checkout
      - run:
          <<: *install_docker_compose
      - attach_workspace:
          at: ~/gravnic-level-creator
      - run: docker-compose up e2e

  deploy: 
    machine: true
    working_directory: ~/gravnic-level-creator
    - add_ssh_keys:
      fingerprints:
        - "8e:5c:ca:37:d9:39:f3:19:61:b2:6d:eb:bd:20:f1:82"
    steps:
      - checkout
      - attach_workspace:
          at: ~/gravnic-level-creator
      - run: bash .circleci/setup-heroku.sh
      - run: heroku git:remote -a $HEROKU_FRONTEND_APP_NAME
      - run: heroku git:remote -a $HEROKU_BACKEND_APP_NAME
      - run: heroku container:login
      - run: cd frontend/
      - run: heroku container:push --app gravnic-frontend web
      - run: cd ../backend/
      - run: heroku container:push --app gravnic-backend web
      - run: sleep 5
      - run: heroku restart

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_frontend
      - frontend_tests:
          requires:
            - build_frontend
      - build_backend
      - backend_tests:
          requires:
            - build_backend
      - e2e_tests:
          requires:
            - frontend_tests
            - backend_tests
      - deploy:
          requires:
            - e2e_tests
          filters:
            branches:
              only: develop
